name: RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test

    container:
      image: ruby:3.2.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up bundler
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Run RSpec
        run: bundle exec rspec --format documentation

      - name: Upload artifacts (screenshots & logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            tmp/screenshots/
            log/test.log

      - name: Upload test results as JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-results
          path: tmp/test-results.xml
